parameters:
#    application_blog.example.class: Application\BlogBundle\Example

services:
#    application_blog.example:
#        class: %application_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
